# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vNo2x3o73R7Sy0t5BBMN1d9XeqdvJlxc
"""

# app.py

import streamlit as st
from scraper import scrape_amazon_product, write_headers, FIELDS, CSV_FILE

# ------------------ Page Config ------------------
st.set_page_config(
    page_title="Amazon Product Scraper",
    page_icon="🛒",
    layout="centered"
)

# ------------------ Header ------------------
st.markdown("""
# 🛍️ Amazon Product Scraper
Easily extract product details from any Amazon product URL.
""")

# ------------------ CSV Setup ------------------
write_headers()

# ------------------ URL Input ------------------
st.markdown("### 🔗 Enter Amazon Product URL")
url = st.text_input("Paste the product URL here", placeholder="https://www.amazon.in/...")

# ------------------ Scrape Button ------------------
if st.button("🚀 Scrape Product"):
    if not url.startswith("http"):
        st.warning("⚠️ Please enter a valid Amazon product URL.")
    else:
        with st.spinner("⏳ Fetching product details..."):
            result = scrape_amazon_product(url)

        if "error" in result:
            st.error(f"❌ An error occurred: {result['error']}")
        else:
            st.success("✅ Product details scraped successfully!")

            # ------------------ Product Image ------------------
            st.image(result["Image URL"], caption=result["Title"], use_column_width=True)

            # ------------------ Product Details ------------------
            st.markdown("### 📦 Product Information")
            for field in FIELDS:
                if field != "Image URL":
                    st.markdown(f"**{field}:** {result[field]}")

            # ------------------ CSV Download ------------------
            with open(CSV_FILE, "rb") as f:
                st.download_button(
                    label="📥 Download Data as CSV",
                    data=f,
                    file_name="amazon_product_data.csv",
                    mime="text/csv"
                )

# ------------------ Footer ------------------
st.markdown("---")
st.caption("Built with ❤️ using Streamlit and BeautifulSoup")